<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Cisco Router Base</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#remove-configuration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#static-route</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#alias</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#write</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#access-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#config-t</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.vlan</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.vrf</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.bgp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.ip.prefix-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.scope.interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.route-map</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(ip)\s+(access-list)\s+(standard|extended)\s+(\S+)\s+$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.base.acl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#permit-ip-any-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.ip</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>alias</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(alias)\s+(bgp\s+\S+|l2\s+\S+|scope\s+address-family\s+\S+|scope\s+\S+|\S+)\s+(\S+)\s+(.*)$</string>
					<key>name</key>
					<string>text.network.cisco.base.alias</string>
				</dict>
			</array>
		</dict>
		<key>config-t</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(configure)\s+(terminal)\s*(?:\s*(\S.*))?$</string>
					<key>name</key>
					<string>text.network.cisco.base.write</string>
				</dict>
			</array>
		</dict>
		<key>permit-ip-any-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>comment</key>
					<string> </string>
					<key>match</key>
					<string>^\s*permit ip any any\s+</string>
					<key>name</key>
					<string>text.network.cisco.base.acl.permit-ip-any-any</string>
				</dict>
			</array>
		</dict>
		<key>static-route</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(ip)\s+(route)(?:\s+(vrf)\s+(\S+))?\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s*(\s+\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.routing.static</string>
				</dict>
			</array>
		</dict>
		<key>write</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(write)(?:\s+(net))?\s*(?:\s*(\S.*))?$</string>
					<key>name</key>
					<string>text.network.cisco.base.write</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base</string>
	<key>uuid</key>
	<string>e5441a2e-8364-4339-b1e2-f79de773f570</string>
</dict>
</plist>
