<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#bgp</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>address-family</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s+(address-family)\s+(ipv4|6)\s+(vrf)\s+(\S+)\s*(\s+\S.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:exit)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.address-family</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#neighbor-remote-as</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-ttl-security-hops</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-timer</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-activate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-inherit-peer-policy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-route-map</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-version</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-shutdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>bgp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(router)\s+(bgp)\s+(\d+)\s*(\s+\S.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#address-family</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#neighbor-remote-as</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>neighbor-activate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(activate)\s*(\s+\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.activate</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-inherit-peer-policy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(inherit)\s+(peer-policy)\s+(\S+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.inherit-peer-policy</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-remote-as</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(remote-as)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.remote-as</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-route-map</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(route-map)\s+(\S+)\s+(in|out)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.route-map</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-shutdown</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(shutdown)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.inherit-peer-policy</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-timer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(timers)\s+(\d+)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.timer</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-ttl-security-hops</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(ttl-security)\s+(hops)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.remote-as</string>
				</dict>
			</array>
		</dict>
		<key>neighbor-version</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(neighbor)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)|\d+)\s+(version)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.bgp.neighbor.version</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.bgp</string>
	<key>uuid</key>
	<string>34955740-df89-4de1-9001-10d53738fa23</string>
</dict>
</plist>
