<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#route-map</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>match-prefix-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(match)\s+(ip)\s+(address)\s+(prefix-list)\s+(\S+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.route-map.match.prefix-list</string>
				</dict>
			</array>
		</dict>
		<key>route-map</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(route-map)\s+(\S+)\s+(?:(permit)|(deny))\s+(\d+)\s*(\s\S.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:exit)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.base.route-map</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-local-preference</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#set-extcommunity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#match-prefix-list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-extcommunity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(set)\s+(extcommunity)\s+(rt)\s+(\d+:\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.route-map.set.extcommunity</string>
				</dict>
			</array>
		</dict>
		<key>set-local-preference</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(set)\s+(local-preference)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.base.route-map.set.local-preference</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.route-map</string>
	<key>uuid</key>
	<string>6d331ea6-7d01-4c6e-a568-0deeb79312e9</string>
</dict>
</plist>
