<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#show-run-int</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#show-int</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>show-int</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)\s*(show)\s+(interface)(?:\s+((?:port-channel|vlan))(?:\s+)?(\d+(?:/\d+)*(?:\.\d+)?))?</string>
					<key>name</key>
					<string>text.network.cisco.base.show.run.interface</string>
				</dict>
			</array>
		</dict>
		<key>show-run-int</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)\s*(show)\s+(run)\s+(interface)(?:\s+((?:port-channel|vlan))(?:\s+)?(\d+(?:/\d+)*(?:\.\d+)?))?</string>
					<key>name</key>
					<string>text.network.cisco.base.show.run.interface</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.show</string>
	<key>uuid</key>
	<string>7e58277e-6948-4150-8d1b-9def2dd1b683</string>
</dict>
</plist>
