<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#do</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#show</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>do</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(do)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>do</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#show</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>running-config</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*((?:running-config)|(?:run))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>running-config</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#n/a</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>show</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(show)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>show</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#running-config</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#startup-config</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>startup-config</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*((?:startup-config)|(?:start))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>startup-config</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#n/a</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>cisco.ace.show</string>
	<key>uuid</key>
	<string>7e5558b5-171e-4364-8eb5-961720a8fa5a</string>
</dict>
</plist>
