<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#logging</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>logging</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(logging)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#logging-enable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-standby</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-timestamp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-trap</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-history</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-buffered</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-persistent</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-queue</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#logging-device-id</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>logging-buffered</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(buffered)\s+([0-7])\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.buffered</string>
				</dict>
			</array>
		</dict>
		<key>logging-device-id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(device-id)\s+(?:(hostname)|(string)\s+(\S+))\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.device-id</string>
				</dict>
			</array>
		</dict>
		<key>logging-enable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(enable)\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.enable</string>
				</dict>
			</array>
		</dict>
		<key>logging-history</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(history)\s+([0-7])\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.history</string>
				</dict>
			</array>
		</dict>
		<key>logging-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(host)\s+((?:\d+\.){3}\d+)(?:\s+(tcp|udp)/(\d+))?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.host</string>
				</dict>
			</array>
		</dict>
		<key>logging-persistent</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(persistent)\s+([0-7])\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.persistent</string>
				</dict>
			</array>
		</dict>
		<key>logging-queue</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(queue)\s+(\d+)\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.queue</string>
				</dict>
			</array>
		</dict>
		<key>logging-standby</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(standby)\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.standby</string>
				</dict>
			</array>
		</dict>
		<key>logging-timestamp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(timestamp)\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.timestamp</string>
				</dict>
			</array>
		</dict>
		<key>logging-trap</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(trap)\s+([0-7])\s*(\S*.*)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.logging.trap</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>cisco.ace.logging</string>
	<key>uuid</key>
	<string>7e5558b5-171e-4364-8eb5-961720a8fa5c</string>
</dict>
</plist>
