<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Cisco ACE ACL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#acl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(access-group)\s+(input|output)\s+(\S+)(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.interface.access-group</string>
				</dict>
			</array>
		</dict>
		<key>acl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(access-list)\s+(\S+)\s+(?:(line)\s+(\d+)\s+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>text.network.cisco.ace.acl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#extended</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>extended</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)(extended)\s+(?:(permit)|(deny))\s+(ip)\s+</string>
					<key>name</key>
					<string>text.network.cisco.ace.acl.extended</string>
				</dict>
			</array>
		</dict>
		<key>nat-pool</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(nat-pool)\s+(\d+)\s+((?:(?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d\s+){2})(netmask)\s+(\S+)\s+(pat)\s*(\s+\S+)?</string>
					<key>name</key>
					<string>text.network.cisco.ace.interface.nat-pool</string>
				</dict>
			</array>
		</dict>
		<key>service-policy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(service-policy)\s+(input|output)\s+(\S+)(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.interface.service-policy</string>
				</dict>
			</array>
		</dict>
		<key>shutdown</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(no\s+shutdown)|(shutdown)(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.interface.shutdown</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.acl</string>
	<key>uuid</key>
	<string>79529eb2-c1de-4465-aab8-0f19daef3f7a</string>
</dict>
</plist>
