<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#class-map</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class-map-http</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class-map-management</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class-map</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(class-map)\s+(match-(?:all|any))\s+(\S+)(\s+\S+)?\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#match-virtual</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>class-map-http</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(class-map)\s+(type)\s+(http)\s+(inspect)\s+(match-(?:all|any))\s+(\S+)(\s+\S+)?\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map-http</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#match-http-content</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#match-http-content-length</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#match-http-header</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#match-http-url</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>class-map-management</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(class-map)\s+(type)\s+(management)\s+(match-(?:all|any))\s+(\S+)(?:\s+(\S.*))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map-management</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#match-protocol</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>match-http-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+\s+)?(match)\s+(content)\s+(\S+)(?:\s+(offset)\s+(\d+))?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map.http.match-content</string>
				</dict>
			</array>
		</dict>
		<key>match-http-content-length</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+\s+)?(match)\s+(content)\s+(length)\s+(?:(eq|gt|lt)\s+(\d+)|(range)\s+(\d+)\s+(\d+))\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map.http.match-content-length</string>
				</dict>
			</array>
		</dict>
		<key>match-http-header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+\s+)?(match)\s+(header)\s+(\S+)\s+(header-value)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map.http.match-header</string>
				</dict>
			</array>
		</dict>
		<key>match-http-url</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+\s+)?(match)\s+(url)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map.http.match-url</string>
				</dict>
			</array>
		</dict>
		<key>match-protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+\s+)?(match)\s+(protocol)\s+(http|https|icmp|icmpv6|kalap-udp|snmp|ssh|telnet|xml-https)\s+(?:(any)|(anyv6)|(source-address)\s+(\S+)(?:\s+(\S+))?)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map.protocol</string>
				</dict>
			</array>
		</dict>
		<key>match-virtual</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d+\s+)?(match)\s+(virtual-address)\s+(\S+)\s+(?:(any)|(?:(tcp|udp)\s+(?:(any)|(?:(eq)\s+(\d+))|(?:(range)\s+(\d+)\s+(\d+)))))\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.class-map.match-virtual</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.class-map</string>
	<key>uuid</key>
	<string>d7c7c43e-beb6-4d6b-9824-85042480b7b8</string>
</dict>
</plist>
