<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#ft-group</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>associate-context</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(associate-context)\s+(\S+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.context.ft-group.associate-context</string>
				</dict>
			</array>
		</dict>
		<key>ft-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(ft)\s+(group)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.ft-group</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#peer</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#priority</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#peer-priority</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#associate-context</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inservice</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>inservice</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(inservice)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.context.ft-group.inservice</string>
				</dict>
			</array>
		</dict>
		<key>peer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(peer)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.context.ft-group.peer</string>
				</dict>
			</array>
		</dict>
		<key>peer-priority</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(peer)\s+(priority)\s+(\d+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.context.ft-group.peer-priority</string>
				</dict>
			</array>
		</dict>
		<key>priority</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(priority)\s+(\S+)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.context.ft-group.priority</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.ft-group</string>
	<key>uuid</key>
	<string>46ec8291-342f-4bc5-b536-f10ba06e9669</string>
</dict>
</plist>
