<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#parameter-map-connection</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>parameter-map-connection</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(parameter-map)\s+(type)\s+(connection)\s+(\S+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>parameter.map.block</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*(?:exit|end)))</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.type.connection</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(set)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-tcp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-tcp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(tcp)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set.tcp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-tcp-buffer-share</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#set-tcp-wan-optimization</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-tcp-buffer-share</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(buffer-share)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set.tcp.buffer-share</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-tcp-buffer-share-buffer</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-tcp-buffer-share-buffer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(\d+)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set.tcp.buffer-share.buffer</string>
				</dict>
			</array>
		</dict>
		<key>set-tcp-wan-optimization</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(wan-optimization)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set.tcp.wan-optimization</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-tcp-wan-optimization-rtt</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-tcp-wan-optimization-rtt</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(rtt)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set.tcp.wan-optimization.rtt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#set-tcp-buffer-share-buffer</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>set-tcp-wan-optimization-rtt-value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(\d+)</string>
					<key>name</key>
					<string>text.network.cisco.base.ace.parameter-map.set.tcp.wan-optimization.rtt.value</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.parameter-map</string>
	<key>uuid</key>
	<string>74a739c6-c377-4803-abad-24139657386f</string>
</dict>
</plist>
