<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#rserver</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inservice</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(inservice)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.rserver.inservice</string>
				</dict>
			</array>
		</dict>
		<key>ip-address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(ip\s+address)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.rserver.ip-address</string>
				</dict>
			</array>
		</dict>
		<key>rserver</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(rserver)\s+(?:(host|redirect)|(\S+))\s+(\S+)(\s+\S+)?\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>meta</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>rserver</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ip-address</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inservice</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.rserver</string>
	<key>uuid</key>
	<string>f330d178-b813-4a4c-a3c1-8b2476ffdc0b</string>
</dict>
</plist>
