<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#serverfarm</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>backup-rserver</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\S*)\s*(backup-rserver)\s+(\S+)?\s*(\S*.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.serverfarm.backup-rserver</string>
				</dict>
			</array>
		</dict>
		<key>inservice</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\S*)\s*(inservice)(\s+standby)?\s*(\S*.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.serverfarm.inservice</string>
				</dict>
			</array>
		</dict>
		<key>predictor-leastconn</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(predictor)\s+(leastconns)(?:\s+(slowstart)\s+(\d+))?\s*(\s+\S.*)?$</string>
					<key>name</key>
					<string>predictor.leastconn</string>
				</dict>
			</array>
		</dict>
		<key>predictor-response</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(predictor)\s+(response)\s+(app-req-to-resp|syn-to-close|syn-to-synack)(?:\s+(samples)\s+(\d+))?\s*(\s+\S.*)?$</string>
					<key>name</key>
					<string>predictor.response</string>
				</dict>
			</array>
		</dict>
		<key>predictor-roundrobin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(predictor)\s+(roundrobin)\s*(\s+\S.*)?$</string>
					<key>name</key>
					<string>predictor.roundrobin</string>
				</dict>
			</array>
		</dict>
		<key>probe</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.cisco.ace.serverfarm.probe</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(probe)\s+(\S+)\s+$</string>
					<key>name</key>
					<string>text.network.cisco.ace.serverfarm.probe</string>
				</dict>
			</array>
		</dict>
		<key>rserver</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s+(rserver)\s+(\S+)\s+(\d+)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.cisco.ace.serverfarm.rserver</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s+(?:desc|dws|faila|inb|par|pre|re|rs|tr))|\S)</string>
					<key>name</key>
					<string>rserver</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#probe</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inservice</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#backup-rserver</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>serverfarm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(serverfarm)\s+(host|redirect)\s+(\S+)\s+(\S.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>serverfarm</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rserver</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#probe</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#predictor-leastconn</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#predictor-roundrobin</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#predictor-response</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.serverfarm</string>
	<key>uuid</key>
	<string>a7ad6885-b478-425a-8b2e-795626f1fd0d</string>
</dict>
</plist>
