<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#acl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>acl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(ip)\s+(access-list)\s+(\S+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>acl.block</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:[^!\s])|(?:\s*exit))</string>
					<key>name</key>
					<string>acl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#seq</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#deny</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>d-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(any)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>d-any</string>
				</dict>
			</array>
		</dict>
		<key>d-network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d/[123]?\d)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>d-network</string>
				</dict>
			</array>
		</dict>
		<key>deny</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(deny)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>deny</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#protocol</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>permit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(permit)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>permit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#protocol</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(ip|tcp|udp)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>protocol</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#s-network</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#s-any</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>s-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(any)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>s-any</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#d-network</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#d-any</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>s-network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d/[123]?\d)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>s-network</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#d-network</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#d-any</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>seq</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(\d+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>sequence</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#deny</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>cisco.nxos.acl</string>
	<key>uuid</key>
	<string>34955740-df89-4de1-9001-10d53738fa23</string>
</dict>
</plist>
