<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface-default</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface-port-type</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>channel-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(channel-group)\s+(\d+)(?:\s+(?:(force)|(?:(mode)\s+(?:(active)|(on)|(passive)))?))?</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.channel-group</string>
				</dict>
			</array>
		</dict>
		<key>interface</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(interface)\s+(Vlan|Ethernet|VLAN|Port-Channel)\s*(\d+(?:/\d+)*(?:\.\d+)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*(?:exit|end)))</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.base.interface</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#service-policy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#spanning-tree-trunk-edge</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#spanning-tree-bpduguard</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#channel-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#vpc</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#no-shutdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#shutdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface-default</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(default)\s+(interface)\s+(Vlan|Ethernet|VLAN|Port-Channel)\s*(\d+(?:/\d+)*(?:\.\d+)?)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.default</string>
				</dict>
			</array>
		</dict>
		<key>interface-port-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)(interface)\s+(Vlan|Ethernet|VLAN|Port-Channel)\s+</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.port-type</string>
				</dict>
			</array>
		</dict>
		<key>no-shutdown</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(no)\s+(shutdown)(?:\s+(\S.*))?</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.ipv4.helper</string>
				</dict>
			</array>
		</dict>
		<key>service-policy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(service-policy)\s+(type)\s+(queuing)\s+(output)\s+(\S+)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.service-policy</string>
				</dict>
			</array>
		</dict>
		<key>shutdown</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(shutdown)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.shutdown</string>
				</dict>
			</array>
		</dict>
		<key>spanning-tree-bpduguard</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.key</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(spanning-tree)\s+(bpduguard)\s+(?:(enable)|(disable))</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.spanning-tree.bpduguard</string>
				</dict>
			</array>
		</dict>
		<key>spanning-tree-trunk-edge</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(spanning-tree)\s+(port)\s+(type)\s+(edge)\s+(trunk)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.spanning-tree.trunk.edge</string>
				</dict>
			</array>
		</dict>
		<key>switchport</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(switchport)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-mode</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport-trunk</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport-access</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(access)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.access</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-access-vlan</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-access-vlan</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(vlan)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.access</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-access-vlan-id</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-access-vlan-id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(\d+)\s+</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.access</string>
				</dict>
			</array>
		</dict>
		<key>switchport-mode</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(mode)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.mode</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-mode-trunk</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport-mode-access</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-mode-access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(access)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.mode.access</string>
				</dict>
			</array>
		</dict>
		<key>switchport-mode-trunk</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?&lt;=\s)(trunk)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.mode.trunk</string>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(trunk)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-encapsulation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-allowed</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(allowed)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.allowed</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed-vlan</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-allowed-vlan</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(vlan)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.allowed.vlan</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed-vlan-add</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed-vlan-remove</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed-vlan-ids</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-allowed-vlan-add</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(add)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.allowed.vlan.add</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed-vlan-ids</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-allowed-vlan-ids</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(?:(?&lt;vlanid&gt;\d+)([,]|[-])?)+</string>
					<key>beginCaptures</key>
					<dict>
						<key>vlanid</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.allowed.vlan.ids</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-encapsulation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-allowed-vlan-remove</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(remove)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.allowed.vlan.remove</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-allowed-vlan-ids</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-encapsulation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\s*(encapsulation)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.encapsulation</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport-trunk-encapsulation-dot1q</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-trunk-encapsulation-dot1q</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(dot1q)\s+</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.trunk.encapsulation.dot1q</string>
				</dict>
			</array>
		</dict>
		<key>vpc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(vpc)\s+(\d+)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.vpc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.nxos.interface</string>
	<key>uuid</key>
	<string>a5379637-12c4-488a-ba8c-7f101650b25d</string>
</dict>
</plist>
