<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface-default</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface-port-type</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>channel-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(channel-group)\s+(\d+)(?:\s+(?:(force)|(?:(mode)\s+(?:(active)|(on)|(passive)))?))?</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.channel-group</string>
				</dict>
			</array>
		</dict>
		<key>interface</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(interface)\s+(Ethernet|VLAN|Port-Channel)\s*(\d+(?:/\d+)*(?:\.\d+)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*(?:exit|end)))</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.base.interface</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#service-policy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#spanning-tree-trunk-edge</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#spanning-tree-bpduguard</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#channel-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#vpc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface-default</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(default)\s+(interface)\s+(Ethernet|VLAN|Port-Channel)\s*(\d+(?:/\d+)*(?:\.\d+)?)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.default</string>
				</dict>
			</array>
		</dict>
		<key>interface-port-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)(interface)\s+(Ethernet|VLAN|Port-Channel)\s+</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.port-type</string>
				</dict>
			</array>
		</dict>
		<key>service-policy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(service-policy)\s+(type)\s+(queuing)\s+(output)\s+(\S+)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.service-policy</string>
				</dict>
			</array>
		</dict>
		<key>spanning-tree-bpduguard</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.key</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(spanning-tree)\s+(bpduguard)\s+(?:(enable)|(disable))</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.spanning-tree.bpduguard</string>
				</dict>
			</array>
		</dict>
		<key>spanning-tree-trunk-edge</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(spanning-tree)\s+(port)\s+(type)\s+(edge)\s+(trunk)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.spanning-tree.trunk.edge</string>
				</dict>
			</array>
		</dict>
		<key>vpc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)^\s*(vpc)\s+(\d+)</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.interface.vpc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.nxos.interface</string>
	<key>uuid</key>
	<string>a5379637-12c4-488a-ba8c-7f101650b25d</string>
</dict>
</plist>
