<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nxos</string>
	</array>
	<key>name</key>
	<string>Cisco NXOS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.nxos.bgp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.nxos.interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.nxos.vlan</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base.nxos.show</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.base</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.network.cisco.base.nxos</string>
	<key>uuid</key>
	<string>e5441a2e-8364-4339-b1e2-f79de773f570</string>
</dict>
</plist>
