<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#show-int</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#show-run-int</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>show-int</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)\s*(show)\s+(interface)(?:\s+(ethernet|port-channel|vlan)(?:\s+)?(\d+(?:/\d+)*(?:\.\d+)?))?</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.show.run.interface</string>
				</dict>
			</array>
		</dict>
		<key>show-run-int</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)\s*(show)\s+(run)\s+(interface)(?:\s+(ethernet|port-channel|vlan)(?:\s+)?(\d+(?:/\d+)*(?:\.\d+)?))?</string>
					<key>name</key>
					<string>text.network.cisco.base.nxos.show.interface</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.nxos.show</string>
	<key>uuid</key>
	<string>b1546df2-7c0d-4b83-89a4-b1b2be929f2e</string>
</dict>
</plist>
