<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#access-list</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(ip)\s+(access-list)\s+(extended)\s+(\S+)(?:\.\d+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*(?:exit|end)))</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#permission</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>connection-state</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(established)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.connection-state</string>
				</dict>
			</array>
		</dict>
		<key>destination-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(any)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.dst-any</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#destination-port-operator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#connection-state</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>destination-mask</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.dst-mask</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#destination-port-operator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#connection-state</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>destination-network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.dst-network</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#destination-mask</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>destination-port</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(?:(\d+)|(bgp))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.dst-port</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#connection-state</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>destination-port-operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(eq)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.dst-port-operator</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#destination-port</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>permission</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(?:(permit)|(deny))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.permission</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#protocol</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(icmp|tcp|udp|ip)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.protocol</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#source-network</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>source-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(any)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.src-any</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source-port</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#destination-network</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#destination-any</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>source-mask</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.src-ip</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source-port-operator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#destination-network</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>source-network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.src-network</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source-mask</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>source-port</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(?:(\d+)|(bgp))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.src-port</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#destination-network</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#destination-any</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>source-port-operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(?:(eq))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.acl.src-port-operator</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#source-port</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>switchport-access-vlan</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.vlan.id</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(switchport)\s+(access)\s+(?:(vlan)\s+(\d+)?)?</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.interface.switchport.access</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.ios.acl</string>
	<key>uuid</key>
	<string>f3e93a29-a010-4073-8877-672418496fd4</string>
</dict>
</plist>
