<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ios</string>
	</array>
	<key>name</key>
	<string>Cisco IOS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#remove-configuration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#alias</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#access-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ios.vlan</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ios.vrf</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ios.bgp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ios.ip.prefix-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ios.interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ios.route-map</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(ip access-list)\s+(standard|extended)\s+(\S+)\s+$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ios.acl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#permit-ip-any-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.ip</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>alias</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(alias)\s+(bgp\s+\S+|l2\s+\S+|scope\s+address-family\s+\S+|scope\s+\S+|\S+)\s+(\S+)\s+(.*)$</string>
					<key>name</key>
					<string>text.network.cisco.ios.alias</string>
				</dict>
			</array>
		</dict>
		<key>permit-ip-any-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>comment</key>
					<string> </string>
					<key>match</key>
					<string>^\s*permit ip any any\s+</string>
					<key>name</key>
					<string>text.network.cisco.ios.acl.permit-ip-any-any</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ios</string>
	<key>uuid</key>
	<string>e5441a2e-8364-4339-b1e2-f79de773f570</string>
</dict>
</plist>
