<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#ip</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interface</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)([^\d\s]+)\s*?(\d+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.interface</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#next-hop</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ip</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*?(ip)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#route</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>mask</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.mask</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interface</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#next-hop</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(name)\s+(\S+)\s*?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.name</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#permanent</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#track</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.network</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mask</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>next-hop</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)((?:\d+\.){3}\d+)\s*?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.next-hop</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#permanent</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#track</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>permanent</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(permanent)\s*?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.permanent</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>route</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(route)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#vrf</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#network</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(tag)\s+(\d+)\s*?</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.tag</string>
				</dict>
			</array>
		</dict>
		<key>track</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(track)\s+(\d+)\s*?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.track</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>vrf</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(vrf)\s+(\S+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.base.ios.ip.route.vrf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#network</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.ios.ip</string>
	<key>uuid</key>
	<string>c6d683e0-8d6b-401c-9762-acaea7667b26</string>
</dict>
</plist>
