<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#logging-host</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>logging-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?i)\s*(logging)\s+((?:\d+\.){3}\d+)\s+</string>
					<key>name</key>
					<string>logging-host</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>cisco.ios.logging</string>
	<key>uuid</key>
	<string>9c962a32-2eb3-482f-95a6-fdf5afe8fb9e</string>
</dict>
</plist>
