<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#vty</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(access-class)\s+(\d+)\s+(in)(?:\s+(vrf-also))?</string>
					<key>name</key>
					<string>access-class</string>
				</dict>
			</array>
		</dict>
		<key>transport</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\s*(transport)\s+(input)\s+(telnet|ssh)(?:\s+(telnet|ssh))?</string>
					<key>name</key>
					<string>transport</string>
				</dict>
			</array>
		</dict>
		<key>vty</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*(line)\s+(vty)\s+(\d+)\s+(\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>vty.block</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*(?:exit|end)))</string>
					<key>name</key>
					<string>vty</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#access-class</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#transport</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.base.ios.vty</string>
	<key>uuid</key>
	<string>9c962a32-2eb3-482f-95a6-fdf5a2e8fb9e</string>
</dict>
</plist>
