<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ace</string>
	</array>
	<key>name</key>
	<string>Cisco ACE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#changeto</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#crypto-import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#crypto-verify</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#remove-configuration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ssl-proxy</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#serverfarm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hostname</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#route</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.probe</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.rserver</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.serverfarm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.sticky</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.class-map</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.policy</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.acl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.ace.resource-class</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>certificate-key-import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s*)(-----.*-----)(\s*)
$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(\s*)(-----.*-----)(\s*)
$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.pki.format.base64</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key-data</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>changeto</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>text.network.cisco.ace.changeto</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Keywords</string>
					<key>match</key>
					<string>^(\S*)\s*(changeto)\s+(\S+)\s*(\S*.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.keywords</string>
				</dict>
			</array>
		</dict>
		<key>crypto-import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\S*)\s*(crypto)\s+(import)\s+(\S+)\s+(\S+)\s*(\S*.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.cisco.ace.crypto.import</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=\s*$|\S)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.network.cisco.ace.crypto.import</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#certificate-key-import</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>crypto-verify</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>text.network.cisco.ace.pki.verify</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\S*)\s*(crypto verify)\s+(\S+\s+\S+)\s*(\S*.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.pki.verify</string>
				</dict>
			</array>
		</dict>
		<key>hostname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>text.network.cisco.ace.hostname</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Keywords</string>
					<key>match</key>
					<string>^\s*(hostname)\s+(\S+)\s*(\S*.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.hostname</string>
				</dict>
			</array>
		</dict>
		<key>key-data</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.line</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\S*)(\s*)(\S*)
$</string>
					<key>name</key>
					<string>pki.key.data</string>
				</dict>
			</array>
		</dict>
		<key>remove-configuration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s*no .*)$</string>
					<key>name</key>
					<string>text.network.cisco.ios.remove</string>
				</dict>
			</array>
		</dict>
		<key>route</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(ip\s+route)\s+((?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)\s+((?:(?:255|254|252|248|240|224|192|128|0)\.){3}(?:255|254|252|248|240|224|192|128|0))\s+((?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d)\s*(\s+\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.route</string>
				</dict>
			</array>
		</dict>
		<key>ssl-proxy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(no)?(\S*)\s*(ssl-proxy)\s+(service)\s+(\S+)\s*(\S*.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.cisco.ace.ssl-proxy</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string></string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=\s*$|\S)</string>
					<key>name</key>
					<string>text.network.cisco.ace.ssl-proxy</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace</string>
	<key>uuid</key>
	<string>e5441a2e-8364-4339-b1e2-f79db773f565</string>
</dict>
</plist>
