<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Cisco ACE Policy Map</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#policy-load-balance</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#policy-map</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#policy-map-management</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>deny</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(deny)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.class.deny</string>
				</dict>
			</array>
		</dict>
		<key>drop</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(drop)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.class.drop</string>
				</dict>
			</array>
		</dict>
		<key>forward</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(forward)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.class.forward</string>
				</dict>
			</array>
		</dict>
		<key>loadbalance-policy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(loadbalance\s+policy)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-class.lb-policy</string>
				</dict>
			</array>
		</dict>
		<key>loadbalance-vip-icmp-reply</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(loadbalance\s+vip)\s+(icmp-reply)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-class.lb.icmp-reply</string>
				</dict>
			</array>
		</dict>
		<key>loadbalance-vip-inservice</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(loadbalance\s+vip)\s+(inservice)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-class.lb-vip-inservice</string>
				</dict>
			</array>
		</dict>
		<key>nat-dynamic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(nat\s+dynamic)\s+(\d+)\s+(vlan)\s+(\d+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-class.nat-dynamic</string>
				</dict>
			</array>
		</dict>
		<key>permit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(permit)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.class.permit</string>
				</dict>
			</array>
		</dict>
		<key>policy-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+(class)\s+(class-default|\S+)(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*class\s))</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#loadbalance-policy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#loadbalance-vip-inservice</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#loadbalance-vip-icmp-reply</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nat-dynamic</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-class-management</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+(class)\s+(class-default|\S+)(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-class-management</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#deny</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-lb-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+(class)\s+(class-default|\S+)(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.policy-lb-class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sticky-serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#drop</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#forward</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-load-balance</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(policy-map)\s+(type)\s+(loadbalance)\s+(first-match|genericfirst-match|http\s+first-match|radius\s+first-match|rdp\s+first-match|rtsp\s+first-match|sip\s+first-match)\s+(\S+)\s*(\s+\S+)?\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.load-balance</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#policy-lb-class</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-map</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(policy-map)\s+(multi-match)\s+(\S+)\s*(\s+\S+)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.map</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#policy-class</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-map-management</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(policy-map)\s+(type)\s+(management)\s+(first-match)\s+(\S+)\s*(?:\s+(\S.*))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.map.management</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#policy-class-management</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>serverfarm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(serverfarm)\s+(\S+)(?:\s+(backup)\s+(\S+))?(?:\s+(aggregate-state))?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.class.serverfarm</string>
				</dict>
			</array>
		</dict>
		<key>sticky-serverfarm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(sticky-serverfarm)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.policy.class.sticky-serverfarm</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.policy</string>
	<key>uuid</key>
	<string>2f2986dd-256a-44d3-b551-a5f6535845fa</string>
</dict>
</plist>
