<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Cisco ACE Resource Class</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#resource-class</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>limit-resource-quantity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(limit-resource)\s+(acl-memory|all|buffer syslog|conc-connections|http-comp|mgmt-connections|proxy-connections|regexp|sticky|xlates)\s+(minimum)\s+(\d+(?:\.\d+)?)\s+(maximum)\s+(equal-to-min|unlimited)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.resource-class.quantity</string>
				</dict>
			</array>
		</dict>
		<key>limit-resource-rate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(limit-resource)\s+(rate)\s+(bandwidth|connections|inspect-conn|mac-miss|mgmt-traffic|ssl-connections|syslog)\s+(minimum)\s+(\d+(?:\.\d+)?)\s+(maximum)\s+(equal-to-min|unlimited)\s*(\s\S.*)?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.resource-class.acl.memory</string>
				</dict>
			</array>
		</dict>
		<key>resource-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(resource-class)\s+(\S+)\s*(\s\S.*)?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.resource-class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#limit-resource-quantity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#limit-resource-rate</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.resource-class</string>
	<key>uuid</key>
	<string>4caf4d6d-9457-4c7c-91c9-2a882d3cf4df</string>
</dict>
</plist>
