<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Cisco ACE Sticky</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#sticky-http-cookie</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-http-content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-http-header</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-l4</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-radius</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-rtsp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-sip</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sticky-ip-netmask</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(content)(?:\s+(offset)\s+(\d+))?(?:\s+(length)\s+(\d+))?(?:\s+(begin-pattern)\s+(\S+))?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.content</string>
				</dict>
			</array>
		</dict>
		<key>cookie</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(cookie\s+offset)(\s+\d+)(?:\s+(length)\s+(\d+))?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.cookie</string>
				</dict>
			</array>
		</dict>
		<key>cookie-insert</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(cookie\s+insert)(\s+browser-expire)?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.timeout</string>
				</dict>
			</array>
		</dict>
		<key>cookie-secondary</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(cookie\s+secondary)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.cookie-secondary</string>
				</dict>
			</array>
		</dict>
		<key>replicate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(replicate)\s+(sticky)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.replicate</string>
				</dict>
			</array>
		</dict>
		<key>serverfarm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(serverfarm)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.timeout</string>
				</dict>
			</array>
		</dict>
		<key>static-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(static\s+content)\s+(\S+)\s+(rserver)\s+(\S+)(?:\s+(\d+))?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.static-content</string>
				</dict>
			</array>
		</dict>
		<key>static-cookie-value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(static\s+cookie-value)\s+(\S+)\s+(rserver)\s+(\S+)(?:\s+(\d+))?\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.static-cookie-value</string>
				</dict>
			</array>
		</dict>
		<key>sticky-http-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(http-content)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.content</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#content</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#static-content</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-http-cookie</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(http-cookie)\s+(\S+)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.header-cookie</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.cookie</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cookie-insert</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cookie</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#static-cookie-value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cookie-secondary</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-http-header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(http-header)\s+(\S+)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.header-cookie</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.header</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-ip-netmask</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(ip-netmask|v6-prefix)\s+(\S+)\s+(address)\s+(source|destination|both)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant.header-cookie</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant.header-cookie</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.ip-netmask</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-l4</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(layer4-payload)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.l4</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-radius</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(radius\s+framed-ip)\s+(calling-station-id|username)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.header-cookie</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.http.radius</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-rtsp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(rtsp-header\s+session)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.rtsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sticky-sip</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(sticky)\s+(sip-header)\s+(\S+)\s+(\S+)\s*(?:\s+(\S+))?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.header-cookie</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.sticky.name</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.sip</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#timeout</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#replicate</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#serverfarm</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>timeout</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(timeout)\s+(\d+)\s*(?:\s+(\S+))?$</string>
					<key>name</key>
					<string>text.network.cisco.ace.sticky.timeout</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ace.sticky</string>
	<key>uuid</key>
	<string>fb8d171a-b2d5-422a-a29f-9befd4a70e8f</string>
</dict>
</plist>
