<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Cisco</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#remove-configuration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#end</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#exit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#show-pipes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(!.*)$</string>
					<key>name</key>
					<string>text.network.cisco.comment</string>
				</dict>
			</array>
		</dict>
		<key>end</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(end)\s*(?:\s+(\S.*))?$</string>
					<key>name</key>
					<string>text.network.cisco.end</string>
				</dict>
			</array>
		</dict>
		<key>exit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(exit)\s*(?:\s+(\S.*))?$</string>
					<key>name</key>
					<string>text.network.cisco.exit</string>
				</dict>
			</array>
		</dict>
		<key>remove-configuration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s*no .*)$</string>
					<key>name</key>
					<string>text.network.cisco.remove</string>
				</dict>
			</array>
		</dict>
		<key>show-pipes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\|)\s+(?:(include)|(exclude)|(begin))\s+(.*)(?=\n)</string>
					<key>name</key>
					<string>text.network.cisco.show.pipe</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco</string>
	<key>uuid</key>
	<string>c9ea5cbe-6199-445e-8629-82ed61e98c95</string>
</dict>
</plist>
