<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#aaa-server-host</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#aaa-server-protocol</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#aaa-authentication</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#aaa-accounting</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#aaa-authorization</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>aaa-accounting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(aaa)\s+(accounting)\s+(command|enable console|ssh console|telnet)\s+(\S+)?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.aaa</string>
				</dict>
			</array>
		</dict>
		<key>aaa-authentication</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(aaa)\s+(authentication)\s+(enable|ssh|http)\s+(console)\s+(\S+)\s+(\S+)?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.aaa</string>
				</dict>
			</array>
		</dict>
		<key>aaa-authorization</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(aaa)\s+(authorization)\s+(exec)\s+(authentication-server)\s+(auto-enable)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.aaa</string>
				</dict>
			</array>
		</dict>
		<key>aaa-server-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(aaa-server)\s+(\S+)\s+(\(\S+\))\s+(host)\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:exit)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.asa.aaa-server.host</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#key</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>aaa-server-protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(aaa-server)\s+(\S+)\s+(protocol)\s+(radius|tacacs\+|sdi|nt|ldap|kerberos|http-form)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.aaa-server.protocol</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>key</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(key)\s+(\S+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.aaa-server.host.key</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.aaa-server</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5eda204</string>
</dict>
</plist>
