<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Cisco ASA access-group</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#access-group</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(access-group)\s+(\S+)\s+(in|out)\s+(interface)\s+(\S+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-group</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.access-group</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda210</string>
</dict>
</plist>
