<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#access-list</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(access-list)\s+(\S+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.acl-name.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-line-number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-remark</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-deny</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-information</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-cache</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-cache</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=cached\s)(ACL log flows. total) (\d+)(, denied) (\d+) (\(deny-flow-max) (\d+)(\))\s*\r?\n</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.cache</string>
				</dict>
			</array>
		</dict>
		<key>acl-dest-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(any|any4|any6)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(host)\s+(((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-ip-subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?:\s+)((255|254|252|248|240|224|192|128|0+|\.){7}))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object)\s+([^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-object.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group)\s+([^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-object-group.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-port-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group)\s+([^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-port-object-group.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-port-range</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(range)\s+([a-z0-9-]+\s+[a-z0-9-]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.accesslist.acl-dest-port-range</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port-range.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-port-single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(eq)\s+([a-z0-9-]+)|(gt)\s+([0-9]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.accesslist.acl-dest-port-single</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hitcount</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-inactive</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-hex-id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-extended-deny</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(extended deny)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.deny.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.deny</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-protocol</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-extended-permit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(extended permit)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.permit.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.permit</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-protocol</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-permit-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-hex-id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;= )(0x[0-9a-f]+)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.hex-id</string>
				</dict>
			</array>
		</dict>
		<key>acl-hitcount</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ACL hitcount</string>
					<key>match</key>
					<string>\s*(\(hitcnt=)(\d+)(\))\s*</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.hitcount</string>
				</dict>
			</array>
		</dict>
		<key>acl-inactive</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.deprecated</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ACL Inactive</string>
					<key>match</key>
					<string>\s*(inactive)(?:\s+(\(inactive\)))?\s*</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.inactive</string>
				</dict>
			</array>
		</dict>
		<key>acl-information</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=;\s)(\d+) (elements; name hash:) (0x[0-9a-f]+)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.information</string>
				</dict>
			</array>
		</dict>
		<key>acl-line-number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(line\s+[0-9]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.line-number.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.line-number</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-remark</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-deny</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-log</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ACL logs</string>
					<key>match</key>
					<string>\s*(log)(?:\s+(informational|debugging|notifications)(?:\s+(interval)\s+(\d+))?(?:\s+(disable))?(?:\s+(default))?)?\s*</string>
					<key>name</key>
					<string>variable.parameter.log.asa</string>
				</dict>
			</array>
		</dict>
		<key>acl-permit-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group)\s+([^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.permit-objgrp.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-source-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-object</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(ip|tcp|udp|icmp|gre|esp|ah|(\d+))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.protocol.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.access-list.protocol</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-source-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-object</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-remark</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>ACL remarks</string>
					<key>match</key>
					<string>remark\s+.+</string>
					<key>name</key>
					<string>variable.parameter.asa</string>
				</dict>
			</array>
		</dict>
		<key>acl-source-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(any|any4|any6)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(host)\s+(((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-ip-subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?:\s+)((255|254|252|248|240|224|192|128|0+|\.){7}))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object)\s+([^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-object.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group)\s+([^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-objgrp.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-src-port-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group)\s+([^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-port-object-group.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-port-object-group.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-src-port-range</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(range)\s+([a-z0-9-]+\s+[a-z0-9-]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port-range.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-src-port-single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(eq)\s+([a-z0-9-]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.access-list</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda202</string>
</dict>
</plist>
