<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asa</string>
	</array>
	<key>name</key>
	<string>Cisco ASA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ip_address</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#url</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#router</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#description</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#group-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#port-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#permit-ip-any-any</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#banner</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ip_verify_reverse-path</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mtu</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hostname</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#changeto</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#terminal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#username</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.nat</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.access-group</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.route</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.access-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.object-group</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.system.context</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.aaa-server</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.policy</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.tunnel-group</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>banner</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(banner)\s+(motd|exec)\s+(.+)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.banner</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>changeto</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(changeto)\s+(?:(context)\s+(\S+))|(system)$</string>
					<key>name</key>
					<string>text.network.cisco.asa.changeto</string>
				</dict>
			</array>
		</dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.asa</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(no\s+.*|no sh|shut|shutdown|reload|reset|activate)\s*</string>
				</dict>
			</array>
		</dict>
		<key>group-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(group-object)\s+([A-Za-z0-9_-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.group-object.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.object-name.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.group-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>hostname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(hostname)\s+(\S+)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.hostname</string>
				</dict>
			</array>
		</dict>
		<key>ip_address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s*(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\s*</string>
					<key>name</key>
					<string>constant.numeric.ip-address</string>
				</dict>
			</array>
		</dict>
		<key>ip_verify_reverse-path</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(ip verify reverse-path interface)\s+(\S+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.ip_verify_reverse-path</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>mtu</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(mtu)\s+(\S+)\s+([0-9]+)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.mtu</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:[1-9]+[0-9]*|0)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.asa</string>
				</dict>
			</array>
		</dict>
		<key>permit-ip-any-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(permit ip any any)\b</string>
					<key>name</key>
					<string>invalid.illegal.acl.permit.asa</string>
				</dict>
			</array>
		</dict>
		<key>router</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(router)\s+(?=[A-Za-z-]+[0-9 ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.router.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.router.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#router_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.router-id.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>terminal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(terminal)\s+(width\s([0-9]+))\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.terminal</string>
				</dict>
			</array>
		</dict>
		<key>url</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(https?|t?ftps?|flash|disk[0-9]|scp|ssh|telnet):(?=[A-Za-z0-9_./-])</string>
					<key>end</key>
					<string>(?=\s+)</string>
					<key>name</key>
					<string>string.unquoted.asa</string>
				</dict>
			</array>
		</dict>
		<key>username</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(username)\s+(\S+)\s+(password)\s+(\S+)\s+(encrypted privilege)\s+([0-9]+)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.username</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda201</string>
</dict>
</plist>
