<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asa</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*.+$</string>
	<key>foldingStopMarker</key>
	<string>^\s*!.*$</string>
	<key>name</key>
	<string>Cisco ASA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ip_address</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#url</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#router</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface_clause</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nameif</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#security-level</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#description</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#group-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#port-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#permit-ip-any-any</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.nat</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.access-group</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.route</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.access-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco.asa.object-group</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.asa</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(!).*$\n?</string>
					<key>name</key>
					<string>text.network.cisco.asa.comment</string>
				</dict>
			</array>
		</dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.asa</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(no\s+.*|no sh|shut|shutdown|reload|reset|activate)\b</string>
				</dict>
			</array>
		</dict>
		<key>group-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(group-object)\s+([A-Za-z0-9_-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.group-object.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.object-name.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.group-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface_clause</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(interface|int)\s+(?=[A-Za-z-]+[0-9/. ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.interface</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.interface.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interface_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.cisco.asa.interface</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface_id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(?i:(?i:fast|gigabit|tengigabit|)ethernet|null|bvi|virtual-?[a-z]*|port-channel|fa|gi|e|se|serial|lo|loopback|tun|tunnel|management)(?=\s?[0-9])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.interface.asa</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.interface-id.asa</string>
					<key>end</key>
					<string>([0-9][0-9/. ]*)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.interface-number.asa</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ip_address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\s</string>
					<key>name</key>
					<string>constant.numeric.ip-address</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s|\.)(?:(?:25[6-9]|2[6-9][0-9]|[3-9]?[0-9][0-9]?)\.)\b</string>
					<key>name</key>
					<string>invalid.illegal.ip-address</string>
				</dict>
			</array>
		</dict>
		<key>nameif</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(nameif)\s+([A-Za-z0-9_-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.asa.interface.nameif</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.asa.interface.nameif.name</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.interface.nameif</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:[1-9]+[0-9]*|0)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.asa</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:eq|neq|gt|lt|range|ge|le)\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.asa</string>
				</dict>
			</array>
		</dict>
		<key>permit-ip-any-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(permit ip any any)\b</string>
					<key>name</key>
					<string>invalid.illegal.acl.permit.asa</string>
				</dict>
			</array>
		</dict>
		<key>router</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(router)\s+(?=[A-Za-z-]+[0-9 ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.router.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.router.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#router_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.router-id.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>security-level</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(security-level)\s+(\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.asa.interface.security-level</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.asa.interface.security-level.level</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.asa.interface.security-level</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>url</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(https?|t?ftps?|flash|disk[0-9]|scp|ssh|telnet):(?=[A-Za-z0-9_./-])</string>
					<key>end</key>
					<string>(?=\s+)</string>
					<key>name</key>
					<string>string.unquoted.asa</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda201</string>
</dict>
</plist>
