<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asa</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*.+$</string>
	<key>foldingStopMarker</key>
	<string>^\s*!.*$</string>
	<key>name</key>
	<string>Cisco ASA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ip_address</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#url</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#router</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface_clause</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nameif</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#security-level</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#object_group</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#description</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#network-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#group-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#port-object</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#access-list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#route</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#permit-ip-any-any</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nat</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.network.cisco</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(access-list)\s+([^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.access-list.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.acl-name.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.access-list.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-line-number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-remark</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-deny</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(any|any4|any6)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-any.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(host\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.acl-dest-host.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-ip-subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?:\s+)((255|254|252|248|240|224|192|128|0+|\.){7}))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-ip-subnet.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object\s+[^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-object.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group\s+[^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-object-group.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-port-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group\s+[^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-port-object-group.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-port-range</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(range\s+[a-z0-9-]+\s+[a-z0-9-]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dest-port-range.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port-range.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-dest-port-single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(eq\s+[a-z0-9-]+)|(gt\s+[0-9]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dest-port-range.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dest-port-range.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-log</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-extended-deny</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(extended deny)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.deny.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-protocol</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-extended-permit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(extended permit)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.permit.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-protocol</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-permit-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-line-number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(line\s+[0-9]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.line-number.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-remark</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-permit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-extended-deny</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-log</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>ACL remarks</string>
					<key>match</key>
					<string>\s*log\s*</string>
					<key>name</key>
					<string>variable.parameter.log.asa</string>
				</dict>
			</array>
		</dict>
		<key>acl-permit-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group\s+[^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.permit-objgrp.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-source-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-object</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-protocol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(ip|tcp|udp|icmp|gre|esp|ah)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.protocol.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-source-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-source-object</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-remark</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>ACL remarks</string>
					<key>match</key>
					<string>remark\s+.+</string>
					<key>name</key>
					<string>variable.parameter.asa</string>
				</dict>
			</array>
		</dict>
		<key>acl-source-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(any|any4|any6)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-any.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(host\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-host.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-ip-subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?:\s+)((255|254|252|248|240|224|192|128|0+|\.){7}))\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-ip-subnet.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object\s+[^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-object.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-source-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group\s+[^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.source-objgrp.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-src-port-object-group</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-src-port-object-group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(object-group\s+[^ ]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.json.dest-port-object-group.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.access-list.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-src-port-range</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(range\s+[a-z0-9-]+\s+[a-z0-9-]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dest-port-range.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port-range.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>acl-src-port-single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(eq\s+[a-z0-9-]+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dest-port-range.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#acl-dest-object-group</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#acl-dest-any</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.dest-port.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.asa</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(no\s+.*|no sh|shut|shutdown|reload|reset|activate)\b</string>
				</dict>
			</array>
		</dict>
		<key>description</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>User created objects</string>
					<key>match</key>
					<string>description\s+([^
]+)</string>
					<key>name</key>
					<string>variable.parameter.asa</string>
				</dict>
			</array>
		</dict>
		<key>group-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(group-object)\s+([A-Za-z0-9_-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.group-object.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.object-name.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.group-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface_clause</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(interface|int)\s+(?=[A-Za-z-]+[0-9/. ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.interface</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.interface.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interface_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.cisco.asa.interface</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface_id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(?i:(?i:fast|gigabit|tengigabit|)ethernet|null|bvi|virtual-?[a-z]*|port-channel|fa|gi|e|se|serial|lo|loopback|tun|tunnel|management)(?=\s?[0-9])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.interface.asa</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.interface-id.asa</string>
					<key>end</key>
					<string>([0-9][0-9/. ]*)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.interface-number.asa</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ip_address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\s</string>
					<key>name</key>
					<string>constant.numeric.ip-address</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s|\.)(?:(?:25[6-9]|2[6-9][0-9]|[3-9]?[0-9][0-9]?)\.)\b</string>
					<key>name</key>
					<string>invalid.illegal.ip-address</string>
				</dict>
			</array>
		</dict>
		<key>nameif</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(nameif)\s+([A-Za-z0-9_-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.asa.interface.nameif</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.asa.interface.nameif.name</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.interface.nameif</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nat</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(nat)\s+([^ ]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.nat</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.nat</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nat-interfaces</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nat-after-auto</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nat-source</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nat-after-auto</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(after-auto)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.after-auto</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.nat.after-auto</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nat-source</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(.*$)</string>
							<key>name</key>
							<string>invalid.illegal.cisco.asa.nat.after-auto</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nat-interfaces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*\(([^,]),([^,])\)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.interface.source</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.interface.destination</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.nat.interface</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nat-after-auto</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nat-source</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(.*$)</string>
							<key>name</key>
							<string>invalid.illegal.cisco.asa.nat.interface</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nat-source</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(source)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.source</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.nat.source</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nat-source-static</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nat-source-dynamic</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(.*$)</string>
							<key>name</key>
							<string>invalid.illegal.cisco.asa.nat.source</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>nat-source-dynamic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(dynamic)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.source.dynamic</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.nat.source.dynamic</string>
				</dict>
			</array>
		</dict>
		<key>nat-source-static</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(static)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.nat.source.static</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>cisco.asa.nat.source.static</string>
				</dict>
			</array>
		</dict>
		<key>network-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(network-object)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.network-object.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.network-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#network-object-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#network-object-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#network-object-host</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(?:(host)(?:\s+)((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.network-object.host</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.ip-address</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.network-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-ip-subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?:\s+)((?:255|254|252|248|240|224|192|128|0+|\.){7}))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.ip-address</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.subnet-mask</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.network-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(?:(object)(?:\s+)([A-Za-z0-9_-]+))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.network-object.object</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>cisco.asa.network-object.object-name</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.network-object.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:[1-9]+[0-9]*|0)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.asa</string>
				</dict>
			</array>
		</dict>
		<key>object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(object)\s+(network|service)\s+([A-Za-z0-9_-]+)(?:\s+)?(tcp|udp|tcp-udp)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.object.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.object_type.asa</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.object_name.asa</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.protocol.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.object.asa</string>
				</dict>
			</array>
		</dict>
		<key>object_group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(object-group)\s+(network|service)\s+([A-Za-z0-9_-]+)(?:\s+)?(tcp|udp|tcp-udp)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.object_group.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.object_type.asa</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.object_name.asa</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.protocol.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.object_group.asa</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:eq|neq|gt|lt|range|ge|le)\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.asa</string>
				</dict>
			</array>
		</dict>
		<key>permit-ip-any-any</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:permit ip any any)\b</string>
					<key>name</key>
					<string>invalid.illegal.acl.permit.asa</string>
				</dict>
			</array>
		</dict>
		<key>port-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(port-object)\s+(eq|range)\s+([0-9a-zA-Z]+)(?:\s+)?([0-9a-zA-Z]+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.port-object.asa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.control.asa</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.minport.asa</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.character.maxport.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.port-object.asa</string>
				</dict>
			</array>
		</dict>
		<key>route</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(route)\s+(\S+)\s+(?:((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\s+((?:255|254|252|248|240|224|192|128|0+|\.){7}))\s+((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(\s+\d+)?\s*(\S.*)?</string>
					<key>name</key>
					<string>cisco.asa.route</string>
				</dict>
			</array>
		</dict>
		<key>router</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(router)\s+(?=[A-Za-z-]+[0-9 ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.router.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.router.asa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#router_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.router-id.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>security-level</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(security-level)\s+(\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.asa.interface.security-level</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.asa.interface.security-level.level</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.asa.interface.security-level</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>url</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(https?|t?ftps?|flash|disk[0-9]|scp|ssh|telnet):(?=[A-Za-z0-9_./-])</string>
					<key>end</key>
					<string>(?=\s+)</string>
					<key>name</key>
					<string>string.unquoted.asa</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>User created objects</string>
					<key>match</key>
					<string>\b([A-Z]+[A-Z0-9_ -]*)\b</string>
					<key>name</key>
					<string>variable.parameter.asa</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda201</string>
</dict>
</plist>
