<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interface</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(interface|int)\s+(?=[A-Za-z-]+[0-9/. ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:exit)|(?:\S))</string>
					<key>name</key>
					<string>cisco.asa.interface</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interface_id</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nameif</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ip_address</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ipv6_address</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ipv6-nd-supress-ra</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#vlan</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#security-level</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.cisco.asa.interface</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface_id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(?i:(?i:fast|gigabit|tengigabit|)ethernet|null|bvi|virtual-?[a-z]*|port-channel|fa|gi|e|se|serial|lo|loopback|tun|tunnel|management)(?=\s?[0-9])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.type.interface.asa</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>cisco.asa.interface.id</string>
					<key>end</key>
					<string>([0-9][0-9/. ]*)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.interface-number.asa</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ip_address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(ip address)\s+((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))(?:\s+(standby)\s+((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))?\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.1</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.3</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant.4</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.5</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>constant.numeric.ip-address</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ipv6-nd-supress-ra</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.1</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(ipv6\s+nd\s+supress-ra)</string>
					<key>name</key>
					<string>constant.numeric.ip-address</string>
				</dict>
			</array>
		</dict>
		<key>ipv6_address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.1</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.3</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.4</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(ipv6\s+address)\s+(\S+)(?:\s+(standby)\s+(\S+))?\s*</string>
					<key>name</key>
					<string>constant.numeric.ip-address</string>
				</dict>
			</array>
		</dict>
		<key>nameif</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(nameif)\s+([A-Za-z0-9_-]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.interface.nameif</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>security-level</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(security-level)\s+(\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.interface.security-level</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>vlan</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(vlan)\s+(\d+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.interface.vlan</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.interface</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ca-879f-061aa5dda202</string>
</dict>
</plist>
