<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#enable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#host</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#timestamp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#buffer</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#log-level</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#trap</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#asdm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#device-id</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>buffer</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(logging)\s+(buffer-size)\s+(\d+)</string>
					<key>name</key>
					<string>logging.buffer</string>
				</dict>
			</array>
		</dict>
		<key>device-id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(logging)\s+(device-id)\s+(string)\s+(\S+)</string>
					<key>name</key>
					<string>logging.device-id</string>
				</dict>
			</array>
		</dict>
		<key>enable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(logging)\s+(enable)</string>
					<key>name</key>
					<string>logging.enable</string>
				</dict>
			</array>
		</dict>
		<key>host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(logging)\s+(host)\s+(\S+)\s+(\d+\.\d+\.\d+\.\d+)</string>
					<key>name</key>
					<string>logging.host</string>
				</dict>
			</array>
		</dict>
		<key>log-level</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(logging)\s+(trap|asdm|buffered)\s+(\S+)</string>
					<key>name</key>
					<string>logging.log-level</string>
				</dict>
			</array>
		</dict>
		<key>timestamp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(logging)\s+(timestamp)</string>
					<key>name</key>
					<string>logging.timestamp</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.logging</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda210</string>
</dict>
</plist>
