<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#object_network</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>fqdn</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(fqdn)\s+(\S+)\s*</string>
					<key>name</key>
					<string>text.network.cisco.asa.object.network.fqdn</string>
				</dict>
			</array>
		</dict>
		<key>host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(host)\s+((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.object.network.host</string>
				</dict>
			</array>
		</dict>
		<key>iprange</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(range)\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))\s*</string>
					<key>name</key>
					<string>text.network.cisco.asa.object.network.ip-range</string>
				</dict>
			</array>
		</dict>
		<key>nat</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(nat)\s+(\(\S+,\S+\)\s+)?(static)\s+(\S+)(\s+dns)?\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.object.network.nat</string>
				</dict>
			</array>
		</dict>
		<key>object_network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(object)\s+(network)\s+(\S+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:exit)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.asa.object.network</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#host</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#nat</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#iprange</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#fqdn</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(subnet)\s+((?:\d+\.){3}\d+)\s+((?:\d+\.){3}\d+)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.object.network.subnet</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.object</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda203</string>
</dict>
</plist>
