<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Cisco ASA object-group</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#object-group_service</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#object-group_icmp-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#object-group_network</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>group-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(group-object)\s+(\S+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network.network-object</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>icmp-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(icmp-object)\s+(\S+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.control.asa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.icmp-type.icmp-object</string>
				</dict>
			</array>
		</dict>
		<key>network-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(network-object)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network.network-object</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#network-object-ip-subnet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#network-object-ip-range</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#network-object-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#network-object-host</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(?:(host)(?:\s+)((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network.network-object.host</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-ip-range</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(range)\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))\s+((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network.network-object.ip-range</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-ip-subnet</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*((?:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))(?:\s+)((?:255|254|252|248|240|224|192|128|0+|\.){7}))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network.network-object.ip-subnet</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>network-object-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(?:(object)\s+(\S+))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network.network-object.object</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.network-object.asa</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>object-group_icmp-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(object-group)\s+(icmp-type)\s+(\S+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.icmp-type</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#icmp-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>object-group_network</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(object-group)\s+(network)\s+(\S+)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.network</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#network-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#group-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>object-group_service</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(object-group)\s+(service)\s+([A-Za-z0-9_-]+)(?:\s+)?(tcp|udp|tcp-udp)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.inserted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.service</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#port-object</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>port-object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(port-object)\s+(eq|range)\s+([0-9a-zA-Z]+)(?:\s+)?([0-9a-zA-Z]+)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.inserted.control.asa</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.character</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>text.network.cisco.asa.object-group.service.port-object</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.object-group</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda204</string>
</dict>
</plist>
