<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#policy-map</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#policy-map-dns-inspect</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dns-param-message-length</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s+(message-length)\s+(maximum)\s+(\d+)</string>
					<key>name</key>
					<string>asa.policy.map.inspect.dns.parameters.length.client</string>
				</dict>
			</array>
		</dict>
		<key>dns-param-message-length-client</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s+(message-length)\s+(maximum)\s+(client)\s+(auto)</string>
					<key>name</key>
					<string>asa.policy.map.inspect.dns.parameters.length.client</string>
				</dict>
			</array>
		</dict>
		<key>dns-parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+(parameters)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*class\s))</string>
					<key>name</key>
					<string>asa.policy.map.inspect.dns.parameters</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dns-param-message-length-client</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dns-param-message-length</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+(class)\s+(inspection_default)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:\s*class\s))</string>
					<key>name</key>
					<string>text.network.cisco.asa.policy.policy-class</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#policy-class-inspect</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-class-inspect</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s+(inspect)\s+(dns (\S+)|ftp|h323 h225|h323 ras|ip-options|netbios|rsh|rtsp|skinny|esmtp|sqlnet|sunrpc|tftp|sip|xdmcp|icmp(?:\s+error)?|pptp)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.asa.policy.policy-class.inspect</string>
				</dict>
			</array>
		</dict>
		<key>policy-map</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(policy-map)\s+(global_policy)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.asa.policy.map</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#policy-class</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>policy-map-dns-inspect</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(policy-map)\s+(type)\s+(inspect)\s+(dns)\s+(\S+)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:\n\s*\n)*(?:\s+\S))$)|(?:\S)|(?:class\s))</string>
					<key>name</key>
					<string>text.network.cisco.asa.policy.map.inspect.dns</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dns-parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.policy</string>
	<key>uuid</key>
	<string>2f2986dd-256a-44d3-b552-a5f6535845fa</string>
</dict>
</plist>
