<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>.</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#host</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#location</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#contact</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>contact</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(snmp-server)\s+(contact)\s+(.*)</string>
					<key>name</key>
					<string>snmp-server.contact</string>
				</dict>
			</array>
		</dict>
		<key>host</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(snmp-server)\s+(host)\s+(\S+)\s+(\d+\.\d+\.\d+\.\d+)\s+(community)(\s+[0-7])?\s+(\S+)(?:\s+(version)\s+(1|2c))?</string>
					<key>name</key>
					<string>snmp-server.host</string>
				</dict>
			</array>
		</dict>
		<key>location</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(snmp-server)\s+(location)\s+(.*)</string>
					<key>name</key>
					<string>snmp-server.location</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.asa.snmp-server</string>
	<key>uuid</key>
	<string>8e510814-afc1-45ba-879f-061aa5dda210</string>
</dict>
</plist>
