<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Interface</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.vlan.id</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(access)\s+(vlan)\s+(\d+)</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface.switchport.mode</string>
				</dict>
			</array>
		</dict>
		<key>interface</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(interface)\s+(?=\S+\d+)(\S+\d+(?:\d+/)*(?:\.\d+)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=(?:\s*(?=(?:
\s*
)*(?:\s+\S))$)|(?:\S))</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#switchport</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ip</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#shutdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco.scope</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.network.cisco</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ip</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ipv4</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(ip\s+address)\s+((?:(?:[0-2]?\d?\d)\.){3}[0-2]?\d?\d(?=[^:])(?:(?:\s+(?:(?:255|254|252|248|240|224|192|128|0)\.){3}(?:255|254|252|248|240|224|192|128|0))))(\s+secondary)?(?:\s+(\S.*))?</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface.ip</string>
				</dict>
			</array>
		</dict>
		<key>mode</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(mode)\s+(trunk|access|capture|fabricpath)\s*</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface.switchport.mode</string>
				</dict>
			</array>
		</dict>
		<key>shutdown</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(no\s+shutdown)|(shutdown)\s*$</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface.ip</string>
				</dict>
			</array>
		</dict>
		<key>switchport</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(switchport)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface.switchport</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mode</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#trunk</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#access</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>trunk</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.vlan.id</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(trunk)\s+(allowed\s+vlan)\s+(?:(add)|(remove))?\s+(\d+(?:\s*[,-]\s*(?:\d+))*)</string>
					<key>name</key>
					<string>text.network.cisco.ios.interface.switchport.mode</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.network.cisco.ios.interface</string>
	<key>uuid</key>
	<string>0f297425-7bd7-431d-bfbd-824e3f9aad68</string>
</dict>
</plist>
